[package]
name = "deepkey_integrity"
description = "DeepKey hApp DNA Integrity Zome"
version = "0.0.2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
license = "CAL-1.0"
homepage = "https://github.com/holochain/deepkey"
documentation = "https://github.com/holochain/deepkey"
keywords = ["holochain", "holo", "deepkey", "DPKI", "PKI"]
categories = ["cryptography", "holochain"]
edition = "2021"

[lib]
name = "deepkey_integrity"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
hdk = "=0.0.162"
hdi = "=0.1.9"
serde = "*"      # use whatever serde hdk gives us
thiserror = "1"

[dev-dependencies]
arbitrary = "1.2.0"                                            # Avoid unstable rust in 1.1.4; defeats compilation of unit tests
mockall = "0.11.2"
hdk = { version = "=0.0.162", features = ["mock"] }
hdi = { version = "=0.1.9", features = ["mock", "test_utils"] }
fixt = "0.0.14"
holochain_types = "0.0.68"
rand = "0.8.5"
strum = "0.24.1"
strum_macros = "0.24.3"

[features]
mock = ["hdk/mock", "hdk/test_utils"]
