[package]
name = "deepkey"
description = "DeepKey hApp"
version = "0.0.2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
license = "CAL-1.0"
homepage = "https://github.com/holochain/deepkey"
documentation = "https://github.com/holochain/deepkey"
keywords = ["holochain", "holo", "deepkey", "DPKI", "PKI"]
categories = ["cryptography", "holochain"]
edition = "2021"

[lib]
name = "deepkey"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
deepkey_integrity = { path = "../deepkey_integrity" }
hdk = "=0.0.159"
hdi = "=0.1.7"
serde = "*"                                           # use whatever serde hdk gives us
thiserror = "1"
mockall = "0.11.2"

[dev-dependencies]
fixt = "0.0.14"
holochain_types = "0.0.65"
rand = "0.8.5"
strum = "0.24.1"
strum_macros = "0.24.3"

[features]
mock = ["hdk/mock", "hdk/test_utils"]
